import '../styles/remedy.css';
import '../styles/variables.scss';
import '../styles/typography.scss';
import '../styles/main.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
